name: ldmg
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - auraloss
      - tensorboard
      - torch
      - torchvision
      - torchaudio
      - torchaudio-augmentatinons
      - torchtext
      - lightning
      - numpy
      - pandas
